publish_mode: editorial_workflow

site_url: https://ericrallen.dev

backend:
  name: github
  repo: ericrallen/dev-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: "Blog Posts"
    folder: blog
    create: true
    filter: { field: "postType", value: "blogPost" }
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: postType, label: 'Post Type', widget: select, value: "blogPost", options: [ "blogPost", "archivedPost" ] }
      - { name: body, label: Body, widget: markdown }
  - name: archive
    label: "Archived Posts"
    folder: blog
    create: true
    filter: { field: "postType", value: "archivedPost" }
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: postType, label: 'Post Type', widget: select, value: "archivedPost", options: [ "blogPost", "archivedPost" ] }
      - { name: body, label: Body, widget: markdown }
  - name: project
    label: Project
    folder: project
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: link, label: Link }
      - { name: postType, label: 'Post Type', widget: select, value: "projectPost", options: [ "projectPost" ] }
      - { name: body, label: Body, widget: markdown }
