publish_mode: editorial_workflow

site_url: https://ericrallen.dev

backend:
  name: github
  repo: ericrallen/dev-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: "Blog Posts"
    folder: blog
    create: true
    filter: { field: "postType", value: "blogPost" }
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: postType, label: 'Post Type', widget: hidden, default: "blogPost" }
      - { name: body, label: Body, widget: markdown }
      - { name: featured, label: "Featured Post", widget: boolean, default: false }
  - name: archive
    label: "Archived Posts"
    folder: blog
    create: true
    filter: { field: "postType", value: "archivedPost" }
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: postType, label: 'Post Type', widget: hidden, default: "archivedPost" }
      - { name: body, label: Body, widget: markdown }
  - name: project
    label: Projects
    folder: project
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: link, label: Link }
      - { name: postType, label: 'Post Type', widget: hidden, value: "projectPost" }
      - { name: blurb, label: Blurb }
      - { name: body, label: Body, widget: markdown }
      - { name: featured, label: "Featured Project", widget: boolean, default: false }
